modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://raw.githubusercontent.com/Killarexe/Crystals/master/forge/update.json"
license = "CC0-1.0"

[[mods]]
modId = "crystals"
version = "${version}"
displayName = "Crystals Mod"
authors = "Killar.exe"
description = '''
A small mod witch adds ores crystals...
'''
logoFile = "assets/crystals/title.png"

[[dependencies.crystals]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.crystals]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
