modLoader = "javafml"
loaderVersion = "[20.2,)"
issueTrackerURL = "https://raw.githubusercontent.com/Killarexe/Crystals/master/forge/update.json"
license = "CC0-1.0"

[[mods]]
modId = "crystals"
version = "${version}"
displayName = "Crystals Mod"
authors = "Killar.exe"
description = '''
A small mod witch adds ores crystals...
'''
logoFile = "assets/crystals/icon.png"

[[dependencies.crystals]]
modId = "neoforge"
type = "required"
versionRange = "[20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.crystals]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"
